### ISSUE TITLE
Path to icons

### ISSUE THREAD

**Issue by Taruu** [pooyagolchian/vue-multiple-themes#1]
The path to the icons is relative, not absolute. If routing is used, then the icon indicates the wrong path
The paths should probably look like this?
```css
@font-face {
  font-family: 'icomoon';
  src:  url('/fonts/icomoon.eot?5gakus');
  src:  url('/fonts/icomoon.eot?5gakus#iefix') format('embedded-opentype'),
  url('/fonts/icomoon.ttf?5gakus') format('truetype'),
  url('/fonts/icomoon.woff?5gakus') format('woff'),
  url('/fonts/icomoon.svg?5gakus#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```
